// Code generated by github.com/whyrusleeping/cbor-gen. DO NOT EDIT.

package datasegment

import (
	"fmt"
	"io"
	"math"
	"sort"

	abi "github.com/filecoin-project/go-state-types/abi"
	cid "github.com/ipfs/go-cid"
	cbg "github.com/whyrusleeping/cbor-gen"
	xerrors "golang.org/x/xerrors"
)

var _ = xerrors.Errorf
var _ = cid.Undef
var _ = math.E
var _ = sort.Sort

var lengthBufInclusionProof = []byte{130}

func (t *InclusionProof) MarshalCBOR(w io.Writer) error {
	if t == nil {
		_, err := w.Write(cbg.CborNull)
		return err
	}

	cw := cbg.NewCborWriter(w)

	if _, err := cw.Write(lengthBufInclusionProof); err != nil {
		return err
	}

	// t.ProofSubtree (merkletree.ProofData) (struct)
	if err := t.ProofSubtree.MarshalCBOR(cw); err != nil {
		return err
	}

	// t.ProofIndex (merkletree.ProofData) (struct)
	if err := t.ProofIndex.MarshalCBOR(cw); err != nil {
		return err
	}
	return nil
}

func (t *InclusionProof) UnmarshalCBOR(r io.Reader) (err error) {
	*t = InclusionProof{}

	cr := cbg.NewCborReader(r)

	maj, extra, err := cr.ReadHeader()
	if err != nil {
		return err
	}
	defer func() {
		if err == io.EOF {
			err = io.ErrUnexpectedEOF
		}
	}()

	if maj != cbg.MajArray {
		return fmt.Errorf("cbor input should be of type array")
	}

	if extra != 2 {
		return fmt.Errorf("cbor input had wrong number of fields")
	}

	// t.ProofSubtree (merkletree.ProofData) (struct)

	{

		if err := t.ProofSubtree.UnmarshalCBOR(cr); err != nil {
			return xerrors.Errorf("unmarshaling t.ProofSubtree: %w", err)
		}

	}
	// t.ProofIndex (merkletree.ProofData) (struct)

	{

		if err := t.ProofIndex.UnmarshalCBOR(cr); err != nil {
			return xerrors.Errorf("unmarshaling t.ProofIndex: %w", err)
		}

	}
	return nil
}

var lengthBufInclusionAuxData = []byte{130}

func (t *InclusionAuxData) MarshalCBOR(w io.Writer) error {
	if t == nil {
		_, err := w.Write(cbg.CborNull)
		return err
	}

	cw := cbg.NewCborWriter(w)

	if _, err := cw.Write(lengthBufInclusionAuxData); err != nil {
		return err
	}

	// t.CommPa (cid.Cid) (struct)

	if err := cbg.WriteCid(cw, t.CommPa); err != nil {
		return xerrors.Errorf("failed to write cid field t.CommPa: %w", err)
	}

	// t.SizePa (abi.PaddedPieceSize) (uint64)

	if err := cw.WriteMajorTypeHeader(cbg.MajUnsignedInt, uint64(t.SizePa)); err != nil {
		return err
	}

	return nil
}

func (t *InclusionAuxData) UnmarshalCBOR(r io.Reader) (err error) {
	*t = InclusionAuxData{}

	cr := cbg.NewCborReader(r)

	maj, extra, err := cr.ReadHeader()
	if err != nil {
		return err
	}
	defer func() {
		if err == io.EOF {
			err = io.ErrUnexpectedEOF
		}
	}()

	if maj != cbg.MajArray {
		return fmt.Errorf("cbor input should be of type array")
	}

	if extra != 2 {
		return fmt.Errorf("cbor input had wrong number of fields")
	}

	// t.CommPa (cid.Cid) (struct)

	{

		c, err := cbg.ReadCid(cr)
		if err != nil {
			return xerrors.Errorf("failed to read cid field t.CommPa: %w", err)
		}

		t.CommPa = c

	}
	// t.SizePa (abi.PaddedPieceSize) (uint64)

	{

		maj, extra, err = cr.ReadHeader()
		if err != nil {
			return err
		}
		if maj != cbg.MajUnsignedInt {
			return fmt.Errorf("wrong type for uint64 field")
		}
		t.SizePa = abi.PaddedPieceSize(extra)

	}
	return nil
}

var lengthBufInclusionVerifierData = []byte{130}

func (t *InclusionVerifierData) MarshalCBOR(w io.Writer) error {
	if t == nil {
		_, err := w.Write(cbg.CborNull)
		return err
	}

	cw := cbg.NewCborWriter(w)

	if _, err := cw.Write(lengthBufInclusionVerifierData); err != nil {
		return err
	}

	// t.CommPc (cid.Cid) (struct)

	if err := cbg.WriteCid(cw, t.CommPc); err != nil {
		return xerrors.Errorf("failed to write cid field t.CommPc: %w", err)
	}

	// t.SizePc (abi.PaddedPieceSize) (uint64)

	if err := cw.WriteMajorTypeHeader(cbg.MajUnsignedInt, uint64(t.SizePc)); err != nil {
		return err
	}

	return nil
}

func (t *InclusionVerifierData) UnmarshalCBOR(r io.Reader) (err error) {
	*t = InclusionVerifierData{}

	cr := cbg.NewCborReader(r)

	maj, extra, err := cr.ReadHeader()
	if err != nil {
		return err
	}
	defer func() {
		if err == io.EOF {
			err = io.ErrUnexpectedEOF
		}
	}()

	if maj != cbg.MajArray {
		return fmt.Errorf("cbor input should be of type array")
	}

	if extra != 2 {
		return fmt.Errorf("cbor input had wrong number of fields")
	}

	// t.CommPc (cid.Cid) (struct)

	{

		c, err := cbg.ReadCid(cr)
		if err != nil {
			return xerrors.Errorf("failed to read cid field t.CommPc: %w", err)
		}

		t.CommPc = c

	}
	// t.SizePc (abi.PaddedPieceSize) (uint64)

	{

		maj, extra, err = cr.ReadHeader()
		if err != nil {
			return err
		}
		if maj != cbg.MajUnsignedInt {
			return fmt.Errorf("wrong type for uint64 field")
		}
		t.SizePc = abi.PaddedPieceSize(extra)

	}
	return nil
}

var lengthBufDataAggregationProof = []byte{131}

func (t *DataAggregationProof) MarshalCBOR(w io.Writer) error {
	if t == nil {
		_, err := w.Write(cbg.CborNull)
		return err
	}

	cw := cbg.NewCborWriter(w)

	if _, err := cw.Write(lengthBufDataAggregationProof); err != nil {
		return err
	}

	// t.Inclusion (datasegment.InclusionProof) (struct)
	if err := t.Inclusion.MarshalCBOR(cw); err != nil {
		return err
	}

	// t.AuxDataType (uint64) (uint64)

	if err := cw.WriteMajorTypeHeader(cbg.MajUnsignedInt, uint64(t.AuxDataType)); err != nil {
		return err
	}

	// t.AuxDataSource (datasegment.SingletonMarketSource) (struct)
	if err := t.AuxDataSource.MarshalCBOR(cw); err != nil {
		return err
	}
	return nil
}

func (t *DataAggregationProof) UnmarshalCBOR(r io.Reader) (err error) {
	*t = DataAggregationProof{}

	cr := cbg.NewCborReader(r)

	maj, extra, err := cr.ReadHeader()
	if err != nil {
		return err
	}
	defer func() {
		if err == io.EOF {
			err = io.ErrUnexpectedEOF
		}
	}()

	if maj != cbg.MajArray {
		return fmt.Errorf("cbor input should be of type array")
	}

	if extra != 3 {
		return fmt.Errorf("cbor input had wrong number of fields")
	}

	// t.Inclusion (datasegment.InclusionProof) (struct)

	{

		if err := t.Inclusion.UnmarshalCBOR(cr); err != nil {
			return xerrors.Errorf("unmarshaling t.Inclusion: %w", err)
		}

	}
	// t.AuxDataType (uint64) (uint64)

	{

		maj, extra, err = cr.ReadHeader()
		if err != nil {
			return err
		}
		if maj != cbg.MajUnsignedInt {
			return fmt.Errorf("wrong type for uint64 field")
		}
		t.AuxDataType = uint64(extra)

	}
	// t.AuxDataSource (datasegment.SingletonMarketSource) (struct)

	{

		if err := t.AuxDataSource.UnmarshalCBOR(cr); err != nil {
			return xerrors.Errorf("unmarshaling t.AuxDataSource: %w", err)
		}

	}
	return nil
}

var lengthBufSingletonMarketSource = []byte{129}

func (t *SingletonMarketSource) MarshalCBOR(w io.Writer) error {
	if t == nil {
		_, err := w.Write(cbg.CborNull)
		return err
	}

	cw := cbg.NewCborWriter(w)

	if _, err := cw.Write(lengthBufSingletonMarketSource); err != nil {
		return err
	}

	// t.DealID (abi.DealID) (uint64)

	if err := cw.WriteMajorTypeHeader(cbg.MajUnsignedInt, uint64(t.DealID)); err != nil {
		return err
	}

	return nil
}

func (t *SingletonMarketSource) UnmarshalCBOR(r io.Reader) (err error) {
	*t = SingletonMarketSource{}

	cr := cbg.NewCborReader(r)

	maj, extra, err := cr.ReadHeader()
	if err != nil {
		return err
	}
	defer func() {
		if err == io.EOF {
			err = io.ErrUnexpectedEOF
		}
	}()

	if maj != cbg.MajArray {
		return fmt.Errorf("cbor input should be of type array")
	}

	if extra != 1 {
		return fmt.Errorf("cbor input had wrong number of fields")
	}

	// t.DealID (abi.DealID) (uint64)

	{

		maj, extra, err = cr.ReadHeader()
		if err != nil {
			return err
		}
		if maj != cbg.MajUnsignedInt {
			return fmt.Errorf("wrong type for uint64 field")
		}
		t.DealID = abi.DealID(extra)

	}
	return nil
}

var lengthBufSegmentDesc = []byte{132}

func (t *SegmentDesc) MarshalCBOR(w io.Writer) error {
	if t == nil {
		_, err := w.Write(cbg.CborNull)
		return err
	}

	cw := cbg.NewCborWriter(w)

	if _, err := cw.Write(lengthBufSegmentDesc); err != nil {
		return err
	}

	// t.CommDs (merkletree.Node) (array)
	if len(t.CommDs) > cbg.ByteArrayMaxLen {
		return xerrors.Errorf("Byte array in field t.CommDs was too long")
	}

	if err := cw.WriteMajorTypeHeader(cbg.MajByteString, uint64(len(t.CommDs))); err != nil {
		return err
	}

	if _, err := cw.Write(t.CommDs[:]); err != nil {
		return err
	}

	// t.Offset (uint64) (uint64)

	if err := cw.WriteMajorTypeHeader(cbg.MajUnsignedInt, uint64(t.Offset)); err != nil {
		return err
	}

	// t.Size (uint64) (uint64)

	if err := cw.WriteMajorTypeHeader(cbg.MajUnsignedInt, uint64(t.Size)); err != nil {
		return err
	}

	// t.Checksum ([16]uint8) (array)
	if len(t.Checksum) > cbg.ByteArrayMaxLen {
		return xerrors.Errorf("Byte array in field t.Checksum was too long")
	}

	if err := cw.WriteMajorTypeHeader(cbg.MajByteString, uint64(len(t.Checksum))); err != nil {
		return err
	}

	if _, err := cw.Write(t.Checksum[:]); err != nil {
		return err
	}
	return nil
}

func (t *SegmentDesc) UnmarshalCBOR(r io.Reader) (err error) {
	*t = SegmentDesc{}

	cr := cbg.NewCborReader(r)

	maj, extra, err := cr.ReadHeader()
	if err != nil {
		return err
	}
	defer func() {
		if err == io.EOF {
			err = io.ErrUnexpectedEOF
		}
	}()

	if maj != cbg.MajArray {
		return fmt.Errorf("cbor input should be of type array")
	}

	if extra != 4 {
		return fmt.Errorf("cbor input had wrong number of fields")
	}

	// t.CommDs (merkletree.Node) (array)

	maj, extra, err = cr.ReadHeader()
	if err != nil {
		return err
	}

	if extra > cbg.ByteArrayMaxLen {
		return fmt.Errorf("t.CommDs: byte array too large (%d)", extra)
	}
	if maj != cbg.MajByteString {
		return fmt.Errorf("expected byte array")
	}

	if extra != 32 {
		return fmt.Errorf("expected array to have 32 elements")
	}

	t.CommDs = [32]uint8{}

	if _, err := io.ReadFull(cr, t.CommDs[:]); err != nil {
		return err
	}
	// t.Offset (uint64) (uint64)

	{

		maj, extra, err = cr.ReadHeader()
		if err != nil {
			return err
		}
		if maj != cbg.MajUnsignedInt {
			return fmt.Errorf("wrong type for uint64 field")
		}
		t.Offset = uint64(extra)

	}
	// t.Size (uint64) (uint64)

	{

		maj, extra, err = cr.ReadHeader()
		if err != nil {
			return err
		}
		if maj != cbg.MajUnsignedInt {
			return fmt.Errorf("wrong type for uint64 field")
		}
		t.Size = uint64(extra)

	}
	// t.Checksum ([16]uint8) (array)

	maj, extra, err = cr.ReadHeader()
	if err != nil {
		return err
	}

	if extra > cbg.ByteArrayMaxLen {
		return fmt.Errorf("t.Checksum: byte array too large (%d)", extra)
	}
	if maj != cbg.MajByteString {
		return fmt.Errorf("expected byte array")
	}

	if extra != 16 {
		return fmt.Errorf("expected array to have 16 elements")
	}

	t.Checksum = [16]uint8{}

	if _, err := io.ReadFull(cr, t.Checksum[:]); err != nil {
		return err
	}
	return nil
}
